import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"https://ipma1822-png.github.io","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const clean=(v:unknown,max=12000)=>String(v||'').replace(/\0/g,'').trim().slice(0,max);
function key(){try{const keys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}');return String(keys.default||Object.values(keys)[0]||'')}catch{return Deno.env.get('SUPABASE_ANON_KEY')||''}}
function outputText(result:any){if(typeof result?.output_text==='string')return result.output_text;for(const item of result?.output||[])for(const part of item?.content||[])if(part?.type==='output_text'&&part?.text)return part.text;return'';}
function extractJson(text:string){const raw=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');return JSON.parse(raw);}
const system=`너는 Global News24의 뉴스 편집기자다. 제공된 자료와 웹 검색으로 확인되는 근거만 사용해 독립적인 한국어 뉴스기사를 작성한다. 외부 기사 문장을 그대로 복사하지 않는다. 확인 자료에 없는 인명, 날짜, 수치, 기관, 발언을 만들지 않는다. URL은 본문에 넣지 않는다. AI 작업과정, 프롬프트, 내부 지시문, 대괄호 작업표시를 기사에 노출하지 않는다. 제목은 핵심 사실 중심 25~55자, 부제는 제목을 보완하는 1~2줄, 요약은 120~300자 2~4문장, 본문은 사실이 충분하면 800~1500자와 5개 이상의 짧은 문단으로 작성한다. 사실이 부족하면 억지로 늘리지 말고 missingFacts에 기록한다. 반드시 JSON 하나만 출력한다.`;

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const authorization=req.headers.get('authorization')||'',url=Deno.env.get('SUPABASE_URL')||'',publishable=key();if(!authorization.startsWith('Bearer ')||!url||!publishable)return json({error:'authentication_required',message:'AI OFFICE 로그인이 필요합니다.'},401);const client=createClient(url,publishable,{global:{headers:{Authorization:authorization}},auth:{persistSession:false}}),{data:{user},error}=await client.auth.getUser();if(error||!user)return json({error:'invalid_session',message:'AI OFFICE 로그인 세션을 확인할 수 없습니다.'},401);const allowed=(Deno.env.get('AI_OFFICE_ADMIN_EMAIL')||'class-admin@ipma.kr').toLowerCase();if(String(user.email||'').toLowerCase()!==allowed)return json({error:'forbidden',message:'기사작성 권한이 없습니다.'},403);const input=await req.json(),news=input?.news||{},title=clean(news.title,300),records=Array.isArray(news.sourceRecords)?news.sourceRecords.slice(0,8).map((r:any)=>({type:clean(r.type,30),name:clean(r.name,120),url:clean(r.url,1000),publishedAt:clean(r.publishedAt,60),summary:clean(r.summary,2500),content:clean(r.content,6000)})):[];if(!title||!records.some((r:any)=>r.url||r.summary||r.content))return json({error:'insufficient_source',message:'기사 제목과 확인 가능한 출처자료가 필요합니다.'},400);const openaiKey=Deno.env.get('OPENAI_API_KEY');if(!openaiKey)return json({error:'configuration_missing',message:'서버 AI 기사작성 키가 설정되지 않았습니다.'},503);const prompt=`기사 후보 제목: ${title}\n분류: ${clean(news.category,80)||'종합'}\n발행시각: ${clean(news.publishedAt,60)}\n초기 출처자료 JSON:\n${JSON.stringify(records)}\n\n웹 검색 시 정부·공공기관·당사자 공식 발표를 우선하고, 중요한 사실은 가능하면 2개 이상 출처로 교차확인하라. Google News 중계 주소는 가능하면 실제 원문 주소로 대체하라. 아래 구조로 JSON을 작성하라: {"factPack":{"articleTopic":"","who":[],"what":[],"when":[],"where":[],"why":[],"how":[],"keyFacts":[],"numbers":[],"organizations":[],"people":[],"background":[],"outlook":[],"missingFacts":[],"sourceRecords":[{"type":"official|primary|crosscheck|reference","name":"","url":"https://...","publishedAt":"","verifiedFact":""}]},"verificationStatus":"verified|partial","article":{"title":"","subtitle":"","summary":"","body":"","category":"","tags":[],"imageBrief":"","photoCaption":""}}`;
const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${openaiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:Deno.env.get('GN24_ARTICLE_MODEL')||'gpt-5-mini',instructions:system,input:prompt,tools:[{type:'web_search'}],tool_choice:'auto'})});const result=await ai.json();if(!ai.ok)throw new Error(result?.error?.message||`openai_${ai.status}`);let parsed;try{parsed=extractJson(outputText(result))}catch{throw new Error('AI 기사 결과를 구조화 JSON으로 읽지 못했습니다.')}const article=parsed?.article||{},factPack=parsed?.factPack||{},sourceRecords=(Array.isArray(factPack.sourceRecords)?factPack.sourceRecords:records).filter((r:any)=>/^https?:\/\//.test(clean(r.url,1000)));if(!clean(article.title)||!clean(article.summary)||!clean(article.body))throw new Error('AI가 완성 기사 필수값을 반환하지 않았습니다.');return json({ok:true,article,factPack:{...factPack,sourceRecords},sourceRecords,verificationStatus:parsed.verificationStatus||'partial',model:result.model||'',generatedAt:new Date().toISOString()});}catch(error){console.error(error);return json({error:'smart_article_failed',message:String(error?.message||error)},500)}});
