create table if not exists public.ai_office_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('schedule', 'task', 'meeting', 'article_review')),
  title text not null check (char_length(title) between 1 and 160),
  description text,
  start_at timestamptz,
  end_at timestamptz,
  location text,
  status text not null default 'planned' check (status in ('planned', 'in_progress', 'done', 'cancelled')),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high')),
  organization text,
  dday_enabled boolean not null default false,
  related_entity_type text,
  related_entity_id text,
  source_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_office_items_end_after_start check (end_at is null or start_at is null or end_at >= start_at)
);

create index if not exists ai_office_items_user_start_idx
  on public.ai_office_items (user_id, start_at);
create index if not exists ai_office_items_user_status_idx
  on public.ai_office_items (user_id, status);

alter table public.ai_office_items enable row level security;

create policy "ai_office_items_select_own"
  on public.ai_office_items for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "ai_office_items_insert_own"
  on public.ai_office_items for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "ai_office_items_update_own"
  on public.ai_office_items for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update on public.ai_office_items to authenticated;
revoke all on public.ai_office_items from anon;

create table if not exists public.ai_office_activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entity_type text not null,
  entity_id uuid not null references public.ai_office_items(id) on delete cascade,
  action text not null check (action in ('schedule_created', 'schedule_updated', 'schedule_cancelled', 'task_created', 'task_updated', 'task_completed', 'task_cancelled')),
  summary text not null,
  source_text text,
  created_at timestamptz not null default now()
);

create index if not exists ai_office_activity_log_user_created_idx
  on public.ai_office_activity_log (user_id, created_at desc);

alter table public.ai_office_activity_log enable row level security;

create policy "ai_office_activity_log_select_own"
  on public.ai_office_activity_log for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "ai_office_activity_log_insert_own"
  on public.ai_office_activity_log for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.ai_office_items i
      where i.id = entity_id and i.user_id = (select auth.uid())
    )
  );

grant select, insert on public.ai_office_activity_log to authenticated;
revoke all on public.ai_office_activity_log from anon;

comment on table public.ai_office_items is 'AI OFFICE 2.0 ARIA personal schedule and task memory';
comment on table public.ai_office_activity_log is 'Immutable ARIA item activity history';
